name: Add native binaries to release

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  prebuild:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3
      - name: Install node-gyp
        if: matrix.os == 'windows-latest'
        run: |
          npm install --global node-gyp@latest
      - name: Dependencies
        run: |
          npm install --ignore-scripts
      - name: Build
        run: |
          npx prebuild --target 18.0.0
          npx prebuild --target 20.0.0
          npx prebuild --target 22.0.0
      - name: Upload
        run: |
          npx prebuild --upload-all ${{ secrets.UPLOAD_TOKEN }}
        env:
          MAKEFLAGS: -j4

  prebuild-alpine:
    name: alpine
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - name: Install build deps
        run: |
          apk add g++ make python3
      - uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Dependencies
        run: |
          npm install --ignore-scripts
      - name: Build
        run: |
          npx prebuild --target 18.0.0
          npx prebuild --target 20.0.0
          npx prebuild --target 22.0.0
      - name: Upload
        run: |
          npx prebuild --upload-all ${{ secrets.UPLOAD_TOKEN }}
        env:
          MAKEFLAGS: -j4
